[workspace]
resolver = "2"
members = ["api", "cli", "program"]

[workspace.package]
version = "0.1.4"
edition = "2021"
license = "Apache-2.0"
homepage = "https://ore.supply/entropy"
description = "Secure random number generator on Solana."
documentation = "https://docs.rs/entropy-api/latest/entropy_api/"
repository = "https://github.com/regolith-labs/entropy"
readme = "./README.md"
keywords = ["solana"]

[workspace.dependencies]
anyhow = "1.0"
bincode = "1.3.3"
bytemuck = "1.14"
num_enum = "0.7"
entropy-api = { path = "./api" }
solana-account-decoder = "^2.1"
solana-client = "^2.1"
solana-sdk = "^2.1"
spl-associated-token-account = { version = "6.0", features = ["no-entrypoint"] }
spl-token = { version = "4.0", features = ["no-entrypoint"] }
solana-program = "2.1"
steel = { version = "4.0.2", features = ["spl"] }
thiserror = "1.0"
tokio = { version = "1.37.0", features = ["full"] }
